spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  #文件上传设置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    formcontent:
      filter:
        enabled: false
  # redis
  redis:
    host: 121.4.124.95
    port: 6379
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最小空闲连接
        max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
      # 连接超时时间（毫秒）
      timeout: 5000
      #默认是索引为0的数据库
      database: 0


